spring:
  application:
    name: eureka-server

server:
  port: ${SERVER_PORT:8070}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:eureka1}
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka1:8070/eureka/,http://eureka2:8072/eureka/,http://eureka3:8073/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
   
